"use client";

import { forwardRef } from "react";
import { NumberSet } from "@/components/lotto/number-set";
import type { GeneratedSet } from "@/types/lotto";

interface ShareCardProps {
  id?: string;
  set: GeneratedSet;
  targetRound?: number | null;
}

export const ShareCard = forwardRef<HTMLDivElement, ShareCardProps>(
  ({ id, set, targetRound }, ref) => {
    return (
      <div
        id={id}
        ref={ref}
        className="absolute top-[-9999px] left-[-9999px] flex w-[540px] flex-col overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950 p-10 shadow-2xl"
        style={{
          // For html-to-image explicitly avoid text-rendering bugs
          fontFamily: "system-ui, sans-serif"
        }}
      >
        {/* Subtle background glow */}
        <div className="absolute top-0 right-0 h-64 w-64 -translate-y-1/2 translate-x-1/3 rounded-full bg-indigo-500/20 blur-[80px]" />
        <div className="absolute bottom-0 left-0 h-64 w-64 -translate-x-1/3 translate-y-1/3 rounded-full bg-cyan-500/10 blur-[80px]" />

        <div className="relative z-10 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-indigo-500 to-purple-500 shadow-[0_0_20px_rgba(99,102,241,0.4)]">
              <span className="text-xl font-bold text-white">L</span>
            </div>
            <span className="text-xl font-bold tracking-tight text-white">
              Lotto Maker Lab
            </span>
          </div>
          <span className="rounded-full border border-white/20 bg-white/5 px-4 py-1.5 text-xs font-semibold tracking-[0.2em] text-slate-300 uppercase">
            {targetRound ? `${targetRound}회 대상` : "추천 번호"}
          </span>
        </div>

        <div className="relative z-10 mt-12 mb-2">
          <p className="text-sm font-semibold tracking-[0.2em] text-teal-400 uppercase">
            {set.strategy} Strategy
          </p>
          <h2 className="mt-3 text-4xl font-bold tracking-tight text-slate-100">
            {targetRound ? `제 ${targetRound}회 파이널 픽` : "프리미엄 추천 조합"}
          </h2>
          <p className="mt-4 text-base leading-relaxed text-slate-400 max-w-[90%]">
            {set.reason || "과거 당첨 데이터를 기반으로 분석된 알고리즘 조합입니다."}
          </p>
        </div>

        <div className="relative z-10 my-10 rounded-3xl border border-white/10 bg-slate-900/60 p-6 shadow-inner backdrop-blur-md">
          <NumberSet numbers={set.numbers} bonus={set.bonus} wrap={true} className="justify-center gap-4" />
        </div>

        <div className="relative z-10 mt-auto flex items-end justify-between border-t border-white/10 pt-6">
          <div className="flex flex-col gap-1.5 text-[0.8rem] text-slate-500">
            <span className="tracking-widest uppercase">Generated by AI Algorithm</span>
            <span>{new Date(set.generatedAt).toLocaleString("ko-KR")}</span>
          </div>
          <div className="text-sm font-semibold tracking-[0.2em] text-slate-300 uppercase">
            lotto-maker.cloud
          </div>
        </div>
      </div>
    );
  }
);

ShareCard.displayName = "ShareCard";
  
